### ISSUE TITLE
Test: Dummy points make game.pbn: Four Heart basic 2/1 (Seat W, Bid 2)

### ISSUE THREAD

**Issue by antross** [TricksterCards/Bridgit#11]
@RalphLipe looks like this test somehow regressed recently. Can you take a look when you get the chance?

> Failed Dummy points make game.pbn: Four Heart basic 2/1 (Seat W, Bid 2) [14 ms]
>   Error Message:
>    `Assert.AreEqual failed. Expected:<4H>. Actual:<3H>.`

**Comment by RalphLipe** [comment]
2/1 game force changed the appropriate response from 4H to 3H for 2nd bid.  Changed test.  Now passing.

**Comment by antross** [comment]
@RalphLipe thanks!
